// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/google": {
            "get": {
                "description": "Redirects the user to Google's OAuth2 consent screen for SSO login. If the user does not have an account, one will be created automatically upon callback.",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Begin Google SSO authentication",
                "parameters": [
                    {
                        "type": "string",
                        "description": "OAuth provider (must be 'google')",
                        "name": "provider",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Redirect to Google consent screen"
                    }
                }
            }
        },
        "/auth/google/callback": {
            "get": {
                "description": "Handles the OAuth2 callback from Google after user consent. Exchanges the authorization code for user info, creates a new account if the user does not exist, generates session and CSRF tokens, and redirects to the frontend.",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Google SSO callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization code from Google",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "OAuth state parameter",
                        "name": "state",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Granted OAuth scopes",
                        "name": "scope",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "307": {
                        "description": "Redirect to frontend with session cookies set"
                    },
                    "400": {
                        "description": "Missing authorization code",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "OAuth or user creation error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/event/create": {
            "post": {
                "description": "While the user is logged in, creates an event and registers it in the database",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Create event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User's CSRF Token",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Event name",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Event theme",
                        "name": "theme",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Event description",
                        "name": "description",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Organization responsable for the event",
                        "name": "organization",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date/Time at which the event starts (RFC3339/ISO8601 format)",
                        "name": "startDate",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date/Time at which the event ends (RFC3339/ISO8601 format)",
                        "name": "endDate",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Location where the event takes place",
                        "name": "location",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Event created with success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error found during event creation",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/event/delete": {
            "post": {
                "description": "A user can delete an event organized by them",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Delete event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User's CSRF Token",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the event",
                        "name": "eventID",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Event deleted with success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "User is not the organizer of the event",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Event not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error found during event deletion",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/event/edit": {
            "post": {
                "description": "A user can edit one of their events",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Edit event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User's CSRF Token",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the event",
                        "name": "eventID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Event name",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Event theme",
                        "name": "theme",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Event description",
                        "name": "description",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Organization responsable for the event",
                        "name": "organization",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Date/Time at which the event starts (RFC3339/ISO8601 format)",
                        "name": "startDate",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Date/Time at which the event ends (RFC3339/ISO8601 format)",
                        "name": "endDate",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Location where the event takes place",
                        "name": "location",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Event edited with success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error found during event editing",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/event/list": {
            "get": {
                "description": "A user can view and filter all published events",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "List events",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User's CSRF Token",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter the name of the events shown",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "maximum": 50,
                        "type": "integer",
                        "default": 20,
                        "description": "Number of events shown",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Number of events to skip in the search",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.ShortEvent"
                            }
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "No event found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/event/my": {
            "get": {
                "description": "A user can view and filter all of their events",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "List the user's event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User's CSRF Token",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter the name of the events shown",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "maximum": 50,
                        "type": "integer",
                        "default": 20,
                        "description": "Number of events shown",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Number of events to skip in the search",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.ShortEvent"
                            }
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "No event found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/event/my/enroll": {
            "get": {
                "description": "A user can view and filter all events that they enrolled in",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "List the user's enrolled event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User's CSRF Token",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter the name of the events shown",
                        "name": "filter",
                        "in": "query"
                    },
                    {
                        "maximum": 50,
                        "type": "integer",
                        "default": 20,
                        "description": "Number of events shown",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Number of events to skip in the search",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.ShortEventEnroll"
                            }
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "No event found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error found on query",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/event/pay": {
            "post": {
                "description": "Dummy endpoint for paying the fee for enrolling in a event",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Event",
                    "Dev"
                ],
                "summary": "Pay event enrollment fee",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User's CSRF Token",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the event",
                        "name": "eventID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "PayToken given during event enrollment",
                        "name": "PayToken",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Event registration payed successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Registration not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Registration has already been paid",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error found during event payment confirmation",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/event/publish": {
            "post": {
                "description": "A user can publish an event organized by them, so that all users can view it",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Publish event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User's CSRF Token",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the event",
                        "name": "eventID",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Event published with success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "User is not the organizer of the event",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Event not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Event already published",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/event/register": {
            "post": {
                "description": "A user can enroll in a event, if said enrollment expects payment, a payToken will be given.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "Enroll in a event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User's CSRF Token",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the event",
                        "name": "eventID",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Discount code",
                        "name": "discountCode",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.PayTokenJSON"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Event / Discount code not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error found during event enrollment",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/event/view/:id": {
            "get": {
                "description": "A user can view the information of an event that they own or was published",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Event"
                ],
                "summary": "View event information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User's CSRF Token",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID of the event",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.LongEvent"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "No event found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Return \"ping\" and log the time in the DB",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dev"
                ],
                "summary": "Example ping endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "Authenticates a user and generates session and CSRF tokens",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "User",
                    "Auth"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User's email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User's password",
                        "name": "pass",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User login with success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Missing email or password",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error found during user login",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/logout": {
            "post": {
                "description": "Logs out the user, clears cookies and resets tokens in DB",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "User",
                    "Auth"
                ],
                "summary": "User logout",
                "parameters": [
                    {
                        "type": "string",
                        "description": "CSRF Token",
                        "name": "X-CSRF-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Logged out successfully!",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/me": {
            "get": {
                "description": "Returns the currently logged in user based on the session token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User",
                    "Auth"
                ],
                "summary": "Get current user",
                "responses": {
                    "200": {
                        "description": "User info",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "Registers an user on the DB",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "User",
                    "Auth"
                ],
                "summary": "User registration",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User's first name",
                        "name": "firstName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User's last name",
                        "name": "lastName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User's role (must be a valid role)",
                        "name": "role",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User's email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "minLength": 8,
                        "type": "string",
                        "description": "User's plain password (must be at least 8 characters long)",
                        "name": "pass",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User registered successfully",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "406": {
                        "description": "Error found on the form params",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Error found on user registration",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.LongEvent": {
            "type": "object",
            "properties": {
                "closed": {
                    "type": "boolean",
                    "example": false
                },
                "description": {
                    "type": "string",
                    "example": "Event's description."
                },
                "endDate": {
                    "type": "string",
                    "example": "2026-03-07T20:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "location": {
                    "type": "string",
                    "example": "Place"
                },
                "name": {
                    "type": "string",
                    "example": "Event"
                },
                "organization": {
                    "type": "string",
                    "example": "Org"
                },
                "organizerID": {
                    "type": "integer",
                    "example": 2
                },
                "published": {
                    "type": "boolean",
                    "example": true
                },
                "startDate": {
                    "type": "string",
                    "example": "2026-03-07T12:00:00Z"
                },
                "theme": {
                    "type": "string",
                    "example": "CompSci"
                }
            }
        },
        "api.PayTokenJSON": {
            "type": "object",
            "properties": {
                "payToken": {
                    "type": "string"
                }
            }
        },
        "api.ShortEvent": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Event"
                },
                "theme": {
                    "type": "string",
                    "example": "CompSci"
                }
            }
        },
        "api.ShortEventEnroll": {
            "type": "object",
            "properties": {
                "confirmed": {
                    "type": "boolean",
                    "example": true
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Event"
                },
                "theme": {
                    "type": "string",
                    "example": "CompSci"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Endpoints only available for development purposes",
            "name": "Dev"
        },
        {
            "description": "Endpoints related with user account management",
            "name": "User"
        },
        {
            "description": "Endpoints related with user authentication",
            "name": "Auth"
        },
        {
            "description": "Endpoints related to event management",
            "name": "Event"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Scientific Event Manager API",
	Description:      "Local Scientific Event Manager System",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
