basePath: /
host: localhost:8080
info:
  contact: {}
  description: Local Scientific Event Manager System
  title: Scientific Event Manager API
  version: "0.1"
paths:
  /event/create:
    post:
      consumes:
      - multipart/form-data
      description: While the user is logged in, creates an event and registers it
        in the database
      parameters:
      - description: User's email
        in: formData
        name: email
        required: true
        type: string
      - description: User's CSRF Token
        in: header
        name: X-CSRF-Token
        required: true
        type: string
      - description: Event name
        in: formData
        name: name
        required: true
        type: string
      - description: Event theme
        in: formData
        name: theme
        required: true
        type: string
      - description: Event description
        in: formData
        name: description
        required: true
        type: string
      - description: Organization responsable for the event
        in: formData
        name: organization
        required: true
        type: string
      - description: Date/Time at which the event starts (RFC3339/ISO8601 format)
        in: formData
        name: startDate
        required: true
        type: string
      - description: Date/Time at which the event ends (RFC3339/ISO8601 format)
        in: formData
        name: endDate
        required: true
        type: string
      - description: Location where the event takes place
        in: formData
        name: location
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "201":
          description: User login with success
          schema:
            type: string
        "401":
          description: Invalid credentials
          schema:
            type: string
        "501":
          description: Error found during event creation
          schema:
            type: string
      summary: Create event
      tags:
      - Event
  /ping:
    get:
      description: Return "ping" and log the time in the DB
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Example ping endpoint
      tags:
      - Dev
  /user/login:
    post:
      consumes:
      - multipart/form-data
      description: Authenticates a user and generates session and CSRF tokens
      parameters:
      - description: User's email
        in: formData
        name: email
        required: true
        type: string
      - description: User's password
        in: formData
        name: pass
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: User login with success
          schema:
            type: string
        "400":
          description: Missing email or password
          schema:
            type: string
        "401":
          description: Invalid credentials
          schema:
            type: string
        "500":
          description: Error found during user login
          schema:
            type: string
      summary: User login
      tags:
      - User
      - Auth
  /user/logout:
    post:
      description: Logs out the user, clears cookies and resets tokens in DB
      parameters:
      - description: User's email
        in: formData
        name: email
        required: true
        type: string
      - description: CSRF Token
        in: header
        name: X-CSRF-Token
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Logged out successfully!
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: User logout
      tags:
      - User
      - Auth
  /user/register:
    post:
      consumes:
      - multipart/form-data
      description: Registers an user on the DB
      parameters:
      - description: User's first name
        in: formData
        name: firstName
        required: true
        type: string
      - description: User's last name
        in: formData
        name: lastName
        required: true
        type: string
      - description: User's role (must be a valid role)
        in: formData
        name: role
        required: true
        type: string
      - description: User's email
        in: formData
        name: email
        required: true
        type: string
      - description: User's plain password (must be at least 8 characters long)
        in: formData
        minLength: 8
        name: pass
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "201":
          description: User registered successfully
          schema:
            type: string
        "406":
          description: Error found on the form params
          schema:
            type: string
        "500":
          description: Error found on user registration
          schema:
            type: string
      summary: User registration
      tags:
      - User
      - Auth
swagger: "2.0"
tags:
- description: Endpoints only available for development purposes
  name: Dev
- description: Endpoints related with user account management
  name: User
- description: Endpoints related with user authentication
  name: Auth
- description: Endpoints related to event management
  name: Event
